version: "3.2"

services:
  spa_postgres:
    build:
      context: .
      dockerfile: Dockerfile.postgres
    ports:
     - 1234:5432

  spa_science_db_graphql_server:
    depends_on:
      - spa_postgres
    build:
      context: .
      dockerfile: Dockerfile.graphql_server
    ports:
      - 3000:3000
    environment:
      - PORT=3000
    # Await POSTGRES role and DB creation, migrate schema, then start web
    # server:
    command: bash -C './migrateDbAndStartServer.sh'

  spa_science_db_app_server:
    depends_on:
      - spa_postgres
      - spa_science_db_graphql_server
    build:
      context: .
      dockerfile: Dockerfile.app
    ports:
      - 8080:8080
    environment:
      - PORT=8080
    command: npm run serve
